CREATE OR REPLACE TABLE adzuna_job_data_analytics (
    id STRING,
    title STRING,
    title_normalized STRING,
    company_name STRING,
    created TIMESTAMP,
    year INT,
    month INT,
    job_category STRING,
    country STRING,
    state STRING,
    city STRING,
    skill_python INT,
    skill_sql INT,
    skill_spark INT,
    skill_hadoop INT,
    skill_aws INT,
    skill_azure INT,
    skill_gcp INT,
    skill_airflow INT,
    skill_databricks INT,
    skill_snowflake INT,
    job_count_city_month INT
);